name: CI
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y ca-certificates gnupg wget
          test -f /usr/share/doc/kitware-archive-keyring/copyright ||
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ noble main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
          sudo apt update
          test -f /usr/share/doc/kitware-archive-keyring/copyright ||
          sudo rm /usr/share/keyrings/kitware-archive-keyring.gpg
          sudo apt install kitware-archive-keyring
          sudo apt update
          sudo apt-get install -y cmake clang clang-tidy qt6-base-dev ca-certificates gpg wget
      - name: Build
        run: |
          mkdir -p build/release
          cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release
          cmake --build build/release --config Release -- -j$(nproc)
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Run tests
        run: ctest --test-dir build/release/tests --output-on-failure
  clang-tidy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Run clang-tidy
        run: |
          ./scripts/clang-tidy.sh
  clang-format:
      runs-on: ubuntu-latest
      needs: build
      steps:
      - name: Format files (clang-format)
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            ./scripts/clang-format.sh
            git add .
            if git diff --cached --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Apply clang-format via CI"
              git push origin ${{ github.ref_name }}
            fi
